[workspace]
resolver = "2"
members = [
    "modeling-cmds",
    "execution-plan",
    "unit-conversion-derive",
]

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
