[package]
name = "unit-conversion-derive"
description = "Derive funtions for unit conversions."
version = "0.1.0"
authors = ["Jess Frazelle <jess@kittycad.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
